set runtimepath^=$X/etc/vim
set runtimepath+=$X/etc/vim/after

filetype off
silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()
filetype indent plugin on
syntax on
set nocompatible
