# 19/x ortak ortam değişkenleri ve ilklendirme dosyası
#
# DİKKAT!  BU DOSYANIN YOKLUĞU HALİNDE X İLKLENDİRME SİSTEMi DEVREDEN
# ÇIKACAKTIR. DOSYADA YAPACAĞINIZ HATALI BİR DEĞİŞİKLİK SİSTEME GİRİŞTE
# SORUNLARA YOL AÇACAKTIR.  AYRINTILI BİLGİ İÇİN KILAVUZU OKUYUN:
#
# 	man x

X_EMAIL=
X_NAME=

. ${X_HOME:=$HOME}/lib/x

# vim:ft=sh
