.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "19\-IRB" "7" "Mart 2011" "19" "19 Kılavuzu"
.
.SH "AÇIKLAMA"
"Etkileşimli Ruby" (\fBi\fRnteractive \fBr\fRu\fBb\fRy) anlamına gelen \fBirb\fR ile Ruby kod denemeleri yapabilirsiniz\.
.
.SH "ÖRNEKLER"
.
.nf

    o                       "o" nesnesini görüntüle
    o\.m                     "o" nesnesini metodlarla birlikte görüntüle
    o\.see                   "o" nesnesini grafik ortamda görselleştir
    o\.ri :metod             "o" nesnesinde \':metod\' dokümanını görüntüle
    o\.interesting_methods   "o" nesnesindeki metodları özet olarak görüntüle

    ri "C#m"                "C" sınıfındaki "m" metoduna ait dokümanı görüntüle

    Clipboard\.copy          Seçileni panoya kopyala
    Clipboard\.paste         Panodan yapıştır

    _                       Bir önceki ifadenin ürettiği sonuç
    var = _                 \'var\' değişkenine bir önceki ifadenin sonucunu ata

    quick       { \.\.\. }     Bloğun ortalama çalışma süresini (100 yinelemeyle) ölç
    quick(1000) { \.\.\. }     Bloğun ortalama çalışma süresini 1000 yinelemeyle ölç

    irb                     Yeni oturum aç
    jobs                    Oturumları listele
    fg 2                    2 numaralı oturuma geç
    exit                    Oturumu kapat  (Ctrl\-D tuşu da kullanılabilir)
    reset!                  Çalışma ortamını sıfırla
    clear                   Ekranı temizle  (Ctrl\-L tuşu da kullanılabilir)

    e                       Son düzenlenen dosyayı aç
    e :b                    "b" referanslı dosyayı, son düzenlenen değişmeden aç
    e!                      Yeni dosya aç
    e! :b                   "b" referanslı dosyayı aç ve son düzenlenen olarak ata
    e?                      Düzenlenecek dosyayı seç
    ed                      Geçici bir dosya aç
.
.fi
.
.SH "YAPILANDIRMA"
Yapılandırma dosyaları \fBetc/irb\fR dizinindedir\.
.
.SH "TELİF HAKKI"
Copyright (C) 2011 19 tayfası \fIhttp://ondokuz\.biz/\fR
.
.SH "BAKINIZ"
Bu kılavuzda \fB19/x\fR kapsamında yapılan düzenlemeler özetlenmektedir\. Programla ilgili daha ayrıntılı bilgi için lütfen aşağıdaki kaynaklara bakın\.
.
.P
irb(1)
.
.P
\fB19/x\fR yapılandırma sistemi hakkında genel bilgi almak için lütfen şu kaynaklara bakın\.
.
.P
19\-x(7)
