.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "19\-SHELL" "7" "Mart 2011" "19" "19 Kılavuzu"
.
.SH "AÇIKLAMA"
TODO
.
.SH "Git"
TODO
.
.SH "Sed"
TODO
.
.SH "Grep"
TODO
.
.SH "Awk"
TODO
.
.SH "Sort"
TODO
.
.SH "TELİF HAKKI"
Copyright (C) 2011 19 tayfası \fIhttp://ondokuz\.biz/\fR
.
.SH "BAKINIZ"
Bu kılavuzda sık kullanılan programlara ilişkin bilgiler özetlenmektedir\. Bu programlarla ilgili daha ayrıntılı bilgi için lütfen programın kendi kılavuz belgesine bakın\.
.
.P
\fB19/x\fR yapılandırma sistemi hakkında genel bilgi almak için lütfen şu kaynaklara bakın\.
.
.P
19\-x(7)
